### ISSUE TITLE
Raygun CLI: TODO

### ISSUE THREAD

**Issue by miquelbeltran** [MindscapeHQ/raygun-toolbox#4]
This ticket compiles all the TODO tasks for Raygun CLI.

- [ ] Support NodeJS projects
- [ ] Distribute binaries (so no Dart SDK is required)
- [ ] Implement tests
- [ ] Support config file for arguments like the `app-id`
- [ ] Support arguments from Env Variables
- [ ] Improve pub.dev score: https://pub.dev/packages/raygun_cli/score
